#!/usr/bin/env python3
"""Generate docs/.snippets/release-notes-table.md.

Zensical's fork of mike invokes `zensical build` as a subprocess (see
`mike/utils.py`), so runtime hooks on Zensical's Python API do not fire
during `mike deploy`. Instead, this script generates the release-notes
table at the source level — `docs/release-notes/index.md` includes the
generated snippet via pymdownx.snippets, and both plain `zensical build`
and `mike deploy` pick it up.

The logic mirrors the previous `hooks.py:on_page_markdown` under MkDocs:
read each `docs/release-notes/*.md` file's frontmatter for `title` and
`description`, sort by dotted numeric version (newest first), emit a
markdown table.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
RELEASE_NOTES_DIR = REPO_ROOT / "docs" / "release-notes"
OUTPUT = REPO_ROOT / "docs" / ".snippets" / "release-notes-table.md"


def _parse_frontmatter(filepath: Path) -> dict:
    content = filepath.read_text()
    match = re.match(r"^---\s*\n(.*?)\n---", content, re.DOTALL)
    if match:
        return yaml.safe_load(match.group(1)) or {}
    return {}


def _version_sort_key(filename: str) -> tuple:
    stem = filename.removesuffix(".md")
    parts = []
    for part in stem.split("."):
        try:
            parts.append(int(part))
        except ValueError:
            parts.append(0)
    return tuple(parts)


def main() -> int:
    if not RELEASE_NOTES_DIR.is_dir():
        print(f"error: {RELEASE_NOTES_DIR} not found", file=sys.stderr)
        return 1

    rn_files = [
        f.name
        for f in RELEASE_NOTES_DIR.iterdir()
        if f.suffix == ".md" and f.name != "index.md"
    ]
    rn_files.sort(key=_version_sort_key, reverse=True)

    rows = []
    for fname in rn_files:
        meta = _parse_frontmatter(RELEASE_NOTES_DIR / fname)
        slug = fname.removesuffix(".md")
        title = meta.get("title", slug)
        description = meta.get("description", "")
        link = f'<a href="../{slug}/" style="white-space: nowrap">{title}</a>'
        rows.append(f"| {link} | {description} |")

    table = (
        "<!-- Auto-generated by scripts/generate_release_notes_table.py. -->\n"
        "\n"
        "| Release | Summary |\n"
        "| --- | --- |\n"
        + "\n".join(rows)
        + "\n"
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(table)
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(rn_files)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
